### ISSUE TITLE
rem2dav Error: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by PorcelainMouse** [jspricke/remind-caldav#15]
Thanks for making this great tool available.  I've wanted to do this for a while, and I think this tool is the best choice.

I get this error when trying rem2dav.  Here is my command line:
`rem2dav --davurl URL --davuser USER --startdate 2022-03-18 --month 1 ~/.reminders.holidays`
where I've redacted my personal information and put my credentials in the keyring.

I'm not quite sure where to start troubleshooting.  Does this mean the conversion from .reminders to JSON encoded CalDAV events is not working?

When I tried dav2rem, as a comparison, I also got an different type of error:
```
Traceback (most recent call last):                                                                   
  File "/usr/lib64/python3.10/zoneinfo/_common.py", line 12, in load_tzdata      
    return importlib.resources.open_binary(package_name, resource_name)
  File "/usr/lib64/python3.10/importlib/resources.py", line 43, in open_binary
    package = _common.get_package(package)                                                           
  File "/usr/lib64/python3.10/importlib/_common.py", line 66, in get_package
    resolved = resolve(package)                                                                      
  File "/usr/lib64/python3.10/importlib/_common.py", line 57, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)                                   
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load                              
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                   
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import                            
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'                                                        
                                                                                                     
During handling of the above exception, another exception occurred:
                                                                                                     
Traceback (most recent call last):                                                                   
  File "/home/<username>/.local/bin/dav2rem", line 8, in <module>
    sys.exit(main())                                                                                 
  File "/home/<username>/.local/lib/python3.10/site-packages/dav2rem.py", line 60, in main
    rem = Remind(args.remfile)                                                                       
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 55, in __init__       
    self._localtz = localtz if localtz else ZoneInfo("localtime")
  File "/usr/lib64/python3.10/zoneinfo/_common.py", line 24, in load_tzdata                       
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key localtime'
```

I installed tzdata pkg, and now I get this:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/usr/lib64/python3.10/importlib/resources.py", line 46, in open_binary
    return reader.open_resource(resource)
  File "/usr/lib64/python3.10/importlib/abc.py", line 433, in open_resource
    return self.files().joinpath(resource).open('rb')
  File "/usr/lib64/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.local/lib/python3.10/site-packages/tzdata/zoneinfo/localtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<username>/.local/bin/dav2rem", line 8, in <module>
    sys.exit(main())
  File "/home/<username>/.local/lib/python3.10/site-packages/dav2rem.py", line 60, in main
    rem = Remind(args.remfile)
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 55, in __init__
    self._localtz = localtz if localtz else ZoneInfo("localtime")
  File "/usr/lib64/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key localtime'
```

I'm not sure what to make of this error either, but I don't understand why my environment isn't being consulted for the time zone.

**Comment by jspricke** [comment]
* PorcelainMouse ***@***.***> [2022-03-18 15:16]:
>I get this error when trying rem2dav.  Here is my command line:
>`rem2dav --davurl URL --davuser USER --startdate 2022-03-18 --month 1 ~/.reminders.holidays`

Can you share the complete traceback?
What DAV server do you use?

>FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.local/lib/python3.10/site-packages/tzdata/zoneinfo/localtime'
[..]
>I'm not sure what to make of this error either, but I don't understand why my environment isn't being consulted for the time zone.

The seems to be the same problem as in

https://github.com/jspricke/python-remind/issues/15

can you try a similar workaround?

**Comment by PorcelainMouse** [comment]
> Can you share the complete traceback?

Oh, dang, sorry.  I got side tracked with my troubleshooting and forgot what I was actually reporting!  Here you go:

```
Traceback (most recent call last):
  File "/home/<username>/.local/bin/rem2dav", line 8, in <module>
    sys.exit(main())
  File "/home/<username>/.local/lib/python3.10/site-packages/rem2dav.py", line 96, in main
    vobject = remind.to_vobject()
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 336, in to_vobject
    self._update()
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 263, in _update
    self._reminders = self._parse_remind(self._filename)
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 110, in _parse_remind
    for month in loads(process.stdout):
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
> What DAV server do you use?

Hmm, I'm not sure what specific DAV server I'm using; It's whatever 'the Helm' uses.  I could ask, though, they have excellent support.  Online docs say "standard CalDAV", and they recommend this third party tool for Outlook sync: https://caldavsynchronizer.org/.  Plus, I got it working with both the default Android calendar app and Etar.  Seems pretty standard.

> FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.local/lib/python3.10/site-packages/tzdata/zoneinfo/localtime'
> The seems to be the same problem as in [jspricke/python-remind#15](https://github.com/jspricke/python-remind/issues/15) can you try a similar workaround?

Hmm, yeah, thanks; that does look like the same issue...
Okay, so, I downgraded my `remind` pkg to 0.17.0 and that resolved the TZ issue with `dav2rem`, but then `dav2rem` failed with the same error as `rem2dav`.

```
Traceback (most recent call last):
  File "/home/<username>/.local/bin/dav2rem", line 8, in <module>
    sys.exit(main())
  File "/home/<username>/.local/lib/python3.10/site-packages/dav2rem.py", line 61, in main
    ldict = set(rem.get_uids())
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 242, in get_uids
    self._update()
  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 224, in _update
    self._reminders = self._parse_remind(self._filename)
  File "/home/zv/.local/lib/python3.10/site-packages/remind.py", line 88, in _parse_remind
    for month in loads(process.stdout):
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
So, at least the two scripts are consistent, once I get beyond the TZ issue.

But, I'm not sure about that symlink workaround, though. I don't think "localtime" is a legitimate TZ to ask for.  I see how the symlink would work, but I think the idiomatic form would be to get the "timezone of the local system" from `datetime`,  then pass that to `Zoneinfo()`.  Would you be interested in such a PR?

- Back to the main issue, now that you see this backtrace, any idea what this is getting at?
- Re: the TZ issue, I think my preferred workaround will be to provide my TZ on the cmdline, since that's an option.

**Comment by jspricke** [comment]
>  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 110, in _parse_remind
[..]
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Odd, the Python can't parse the json output of Remind. Which version of Remind
do you use?
What is the output of `remind -ppp <file.rem>`?

> I don't think "localtime" is a legitimate TZ to ask for.

What do you think so?

> I see how the symlink would work, but I think the idiomatic form would be to get the "timezone of the local system" from `datetime`,  then pass that to `Zoneinfo()`.  Would you be interested in such a PR?

Depends on how much code it would be to make it work.

The tzlocal package has functions to provide the location of `localtime` to
Python but my feeling is that this should be rather solved in Python or the
Python distributions.

**Comment by PorcelainMouse** [comment]
> > File "/home//.local/lib/python3.10/site-packages/remind.py", line 110, in _parse_remind
> > [..]
> > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> Odd, the Python can't parse the json output of Remind. Which version of Remind do you use? What is the output of `remind -ppp <file.rem>`?

```
$ remind -ppp remindTRY3.txt 
# rem2ps begin
March 2022 31 2 0
Sunday Monday Tuesday Wednesday Thursday Friday Saturday
February 28
April 30
2022/03/02 * * * * Ash Wednesday
2022/03/07 * FOO 60 600 10:00-11:00am Meeting
2022/03/08 * * * * International Women's Day
2022/03/12 * * * * National Pancake
2022/03/13 * * * 119 1:59am DST: spring forward 1 hour
2022/03/13 * * * * DST begins
2022/03/14 * FOO 60 600 10:00-11:00am Meeting
2022/03/14 * * * * National Pi Day
2022/03/15 * * * * Everything You Think Is Wrong
2022/03/17 * * * * St. Patrick's
2022/03/20 * * * * Spring Equinox
2022/03/21 * FOO 60 600 10:00-11:00am Meeting
2022/03/22 * * * * World Water Day
2022/03/28 * FOO 60 600 10:00-11:00am Meeting
2022/03/30 * FOO 60 600 10:00-11:00am Meeting
# rem2ps end
```

remind version 3.01.15.  My distro hasn't updated remind in several releases.

> > I don't think "localtime" is a legitimate TZ to ask for.
> 
> Why do you think so?

Because "localtime" isn't a timezone.  It's the name of a file in `/etc` that points to the right timezone file, but that's not a valid value type to pass to ZoneInfo(). Plus, it's a platform-specific convention.

The documentation for `zoneinfo` says "By default, zoneinfo uses the system’s time zone data if available", but, in true Python form, doesn't explain that particular usage at all.  Since you cannot call ZoneInfo(None), I don't see how it could return a "default" object.  In Linux, the system has both the TZ env var and /etc/localtime to help you, but I read that no such standard is available on other platforms, so...

`datetime.datetime.now()` returns a time obj in the local timezone, so if the --zone parameter isn't provided, I would think that would be the way, no?  Although, I read this is also not guaranteed to work, either.  On the other hand, I also read people saying that there is no fail-safe, cross-platform way to do this in Python.

```
$ python3 -c 'from datetime import datetime; print(datetime.now().astimezone().tzinfo)'
PDT
```

> The tzlocal package has functions to provide the location of `localtime` to Python but my feeling is that this should be rather solved in Python or the Python distributions.

Yes, I read that is not the preferred solution, either.  But, I also don't think it is or will be solved "in Python".  I certainty don't think this is a problem `remind-caldav` needs to solve, though.  You already implemented the parameter to push this requirement to the user, so that could just be a required option.  Or, maybe you catch `zoneinfo._common.ZoneInfoNotFoundError` and then report the need to specify it.

Also, it's not clear to me if tzdata is really required or not. Should it be a dependency?  I don't get any error if I specify --zone and `tzdata` isn't installed.  I don't think it should be required on Linux...hmm, yeah, right, it couldn't find the 'localtime' TZ file, so I tried to import tzdata...okay, so no that's just another symptom of the same issue.

**Comment by jspricke** [comment]
>remind version 3.01.15.  My distro hasn't updated remind in several releases.

You need at least version 03.03.01, I will add an error message later.

>`datetime.datetime.now()` returns a time obj in the local timezone, so if the --zone parameter isn't provided, I would think that would be the way, no?  Although, I read this is also not guaranteed to work, either.  On the other hand, I also read people saying that there is no fail-safe, cross-platform way to do this in Python.
>
>```
>$ python3 -c 'from datetime import datetime; print(datetime.now().astimezone().tzinfo)'
>PDT
>```

Nice, I was not aware. I will look into using that as the source later.

**Comment by PorcelainMouse** [comment]
Thanks for all you help!  I got the latest `remind` version.  Unfortunately, it's still not working, but the symptoms are different and I think we're over this issue.

**Comment by jspricke** [comment]
* PorcelainMouse ***@***.***> [2022-03-19 00:52]:
>  File "/home/<username>/.local/lib/python3.10/site-packages/remind.py", line 110, in _parse_remind
[..]
>json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Odd, the Python can't parse the json output of Remind. Which version of 
Remind do you use?
What is the output of `remind -ppp <file.rem>`?

>I don't think "localtime" is a legitimate TZ to ask for.

What do you think so?

>I see how the symlink would work, but I think the idiomatic form would be to get the "timezone of the local system" from `datetime`,  then pass that to `Zoneinfo()`.  Would you be interested in such a PR?

Depends on how much code it would be to make it work.

The tzlocal package has functions to provide the location of `localtime` 
to Python but my feeling is that this should be rather solved in Python 
or the Python distributions.

**Comment by PorcelainMouse** [comment]
Thanks for working on this.

Looks like you found a the right function to get the local TZ.  I didn't find that.  Cool.

**Comment by jspricke** [comment]
that reply was also really old, sorry again.

**Comment by PorcelainMouse** [comment]
Just wanted to say that I was able to get this working when I tried it just now.  I didn't have to do anything really crazy, FWIW.  Thanks again.
